### ISSUE TITLE
ImportError: cannot import name 'index_update' from 'jax.ops' (/home/home/.local/lib/python3.8/site-packages/jax/ops/__init__.py)

### ISSUE THREAD

**Issue by er1c-cartman** [fatemeh-rastgar/PRIEST#1]
Hi. I've tried to run it but here's an error with jax.
I think it's kind of error due to the jax version
Which version of jax and jaxlib have you used to simulate your package?

Traceback (most recent call last):
  File "/home/home/priest_ws/src/PRIEST/priest/src/planner_holonomic.py", line 21, in <module>
    import mpc_expert
  File "/home/home/priest_ws/src/PRIEST/priest/src/mpc_expert.py", line 9, in <module>
    from jax.ops import index_update, index
ImportError: cannot import name 'index_update' from 'jax.ops' (/home/home/.local/lib/python3.8/site-packages/jax/ops/__init__.py)

Best regards :)

**Comment by fatemeh-rastgar** [comment]
The issue has been solved. 
The previous versions of Jax supported jax.ops, but the new ones do not. Since we are not using index update in the code, This line can be removed from the code.

**Comment by fatemeh-rastgar** [comment]
The issue has been solved.
The previous versions of Jax supported jax.ops, but the new ones do not. Since we are not using index update in the code, This line can be removed from the code.
