### ISSUE TITLE
Question about implementaion of costmap

### ISSUE THREAD

**Issue by er1c-cartman** [fatemeh-rastgar/PRIEST#2]
Hi. I've run your code and it works well.
But is it possible to run with using costmap?
I'm using custom costmap that publishing traversability estimation from 2.5d mapping.
And i want to use my costmap with your planner

Best regards

**Comment by arunkumar-singh** [comment]
HI
The code by itself is not designed for arbitrary cost-map. But we believe it can be done with slight modification to the code base. We would be actually happy to guide you to make this conversion if you can give some more information about the cost-map. What is the format of the cost-map? Is it similar to the common cost-map that ROS navigation stack generates based on Lidar scans? Is it just some black-box code block that takes in a point and returns its cost value?

**Comment by er1c-cartman** [comment]
Hi. thanks for having interest and kind reply :)
i think it's like black box 
I'm using elevation mapping to create 2.5d map and use traversability estimation to make cost map.
So basically using only static layer for navigation

**Comment by arunkumar-singh** [comment]
Is it possible for you to re-implement the cost-map generation as a JAX function?

**Comment by er1c-cartman** [comment]
Due to my poor coding skill, right now it's seems hard to do it.
Sorry
But if there's any progress, I'll reopen the issue
Thanks for having interest on it :)
Best regards
