### ISSUE TITLE
Problem with using planner_nonhol_dy.py and plnner_nonholonomic.py

### ISSUE THREAD

**Issue by er1c-cartman** [fatemeh-rastgar/PRIEST#3]
Hi.
I've run your code "planner holonomic" and other compare stuffs works well with few edit.
I would love to run plnner_nonholonomic.py and planner_nonhol_dy.py but it can't dodge obstacles. Also seems it's not planning path that well.
I've edited few parts to run it, but unfortunately it doesn't works well :(      it keeps heading to wall, can't dodge obstacles
If you can, can you share your code that works well?
I'm really interested in your works. It looks much better than previous approaches
I'm uploading my edit just in case you can check it.

Best regards :) thanks for sharing your amazing work

[edit.zip](https://github.com/fatemeh-rastgar/PRIEST/files/13871829/edit.zip)

**Comment by arunkumar-singh** [comment]
We will look into this and get back to you shortly

**Comment by fatemeh-rastgar** [comment]
Hello,

To run the non-holonomic part, you should execute the "planner_nonhol_dy.py" file. It seems the issues in your script are related to changes in topics and frames. It's important to note that these topics and frames are intentionally selected. Here are a couple of points to consider:

You altered the name of the topic where velocities are published to "jackal_velocity_controller," which is incorrect. I installed Jackal through the log-mppi repository, and the velocities are published with the exact name used in their repository.

You changed the odometry topic, which can result in incorrect information being sent to the robot, leading to improper planning.

Similar issues are present in your launch file as well. Please make sure to use the correct topics and frames as specified in the original code to ensure proper functionality.

**Comment by fatemeh-rastgar** [comment]
Hello,

To run the non-holonomic part, you should execute the "planner_nonhol_dy.py" file. It seems the issues in your script are related to changes in topics and frames. It's important to note that these topics and frames are intentionally selected by us. Here are a couple of points to consider:

You altered the name of the topic where velocities are published to "jackal_velocity_controller," which is incorrect. I installed Jackal through the log-mppi repository, and the velocities are published with the exact name used in their repository.

You changed the odometry topic, which can result in incorrect information being sent to the robot, leading to improper planning.

Similar issues are present in your launch file as well. Please make sure to use the correct topics and frames as specified in the original code to ensure proper functionality.

**Comment by er1c-cartman** [comment]
great. it works well.
1 question
I would love to use nonholonomic robot planner on non dynamic environment, 
so basically want to use plnner_nonholonomic.py file.
First error is there's no theta_init, but I've fixed with giving value on init part
Second error is the code runs but robot doesn't move forward. it's keep turning round and round

and besides, when I run planner_nonhol_dy.py, before robot move, it keep turning around and start to move. Why robot is moving? or is there any reason to make robot turn around?

Best regards :)
