### ISSUE TITLE
code for showing homotopy path

### ISSUE THREAD

**Issue by er1c-cartman** [fatemeh-rastgar/PRIEST#5]
Hi. thanks for sharing your great works
I would love to simulate same with what you've uploaded on youtube
is it possible to share the code that runs exactly same in this video?
best regards

https://www.youtube.com/watch?v=XPKR2AXSnFw&t=19s

**Comment by fatemeh-rastgar** [comment]
Hello, 

We will push the maze code soon as well. However, our optimizer is not designed to work reliably in a maze environment and we only showed a simple example.
