### ISSUE TITLE
Any plan on converting it to ros2 plugin?

### ISSUE THREAD

**Issue by prashan77** [fatemeh-rastgar/PRIEST#6]
Looking at the videos it seems to be performing better than existing ros2 controllers. Is there any plan to convert to ros2 plugins?

**Comment by fatemeh-rastgar** [comment]
> Looking at the videos it seems to be performing better than existing ros2 controllers. Is there any plan to convert to ros2 plugins?

Thanks for your question. Currently we do not have any plan to convert it to ROS2 and are working to improve it from other aspects.
